let suggestions = [
    "Channel",
    "CodingLab",
    "CodingNepal",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
    "COVID-19",  
    "Black Friday deals",  
    "Olympics 2024",  
    "Bitcoin price",  
    "World Cup 2026",  
    "Election results",  
    "How to make bread",  
    "Mental health tips",  
    "Travel restrictions",  
    "Home workout routines",  
    "Cryptocurrency news",  
    "US Open 2024",  
    "AI tools",  
    "NBA Playoffs",  
    "Weather today",  
    "TikTok trends",  
    "iPhone 14 release date",  
    "How to lose weight",  
    "Streaming services",  
    "Mobile games",  
    "Best Netflix shows",  
    "Health and wellness",  
    "Virtual reality",  
    "Mindfulness practices",  
    "Digital marketing trends",  
    "Gardening tips",  
    "Pet care",  
    "Job opportunities",  
    "Online courses",  
    "Personal finance",  
    "Home improvement",  
    "Social media updates",  
    "Parenting advice",  
    "Current events",  
    "Celebrity news",  
    "Food recipes",  
    "Car reviews",  
    "Tech gadgets",  
    "Fashion trends",  
    "Sustainable living"
];
